version: '3.8'

services:
    # The Go App
    task4_1:
        image: 'task4_1_image'
        command: ./task4_1
        container_name: go_app
        ports:
            - '8080:8080'
        env_file:
            - ./.env
        depends_on:
            - mongo
            - redis

    # MongoDB
    mongo:
        image: 'mongo:4.4'
        container_name: mongo
        ports:
            - '27017:27017'
        restart: always

    # Mongo Express Web-based MongoDB admin interface
    mongo_express:
        image: 'mongo-express:0.54.0'
        container_name: mongo_express
        depends_on:
            - 'mongo'
        ports:
            - '8081:8081'
        restart: always

    # Redis
    redis:
        image: 'redis:7.0.10'
        ports:
            - "6379:6379"
